* **Core Initialization (Ядро)**
** описание
   Всё, что связано с базовой загрузкой, включая `init.el`, пакеты и первоначальные настройки.
	 установка пкетменеджеров страйта и юз-пакеджера.
** 
* **UI и интерфейсные улучшения**
** описание
   Темы, powerline, minimap и кастомные элементы интерфейса.

* ** горячие клавиши**
** Буфер и фрейм менеджмент**
*** описание
	 Всё для работы с окнами, фреймами и переключением между ними (`framemove`, `windmove`, fullscreen и т.д.)
** Evil и навигация**
*** описание
	Всё, связанное с `evil-mode`, табами и улучшением навигации по буферам/фреймам.  
** Hydra и горячие клавиши**
*** описание
			Всё, что касается кастомных меню и команд.  
* **Org Mode и интеграции**
** описание
   Все конфиги для `org-mode`, включая `babel`, `org-roam`, `org-brain` и графические инструменты.  
* **Работа с файлами и менеджмент**
** описание
   Конфиги для управления файлами, поиска и т.п.  
* **Литературное и текстовые задачи**
** описание
   Чтение текстов, работа с переводами, tts, `read-aloud`.  
* **Автоматизация и Productivity**
** описание
   Автодополнения, сниппеты и автоматические действия.  
* **Программирование и языковые конфигурации**
** описание
   Отдельные категории для Python, Clojure, JavaScript, Lua и т.д. + автодополнения и проверки синтаксиса.  
* **Мои Elisp скрипты**
** описание
   Персональные расширения и полезные функции.  
* **Архив и Deprecated конфиги**
** описание
    Всё, что уже не используется, но содержит полезные идеи.
* блок для экспериментальных настроек
* Babel-блокам команд

* 2025-02-07

